Acount/urls.py
from django.conf.urls import url

from Account import views

urlpatterns = [
    url(r'^accountlist/', views.accountlist, name='accountlist'),
    url(r'^accountdelete/',views.accountdelete),
    url(r'^accountstart/',views.accountstart),
    url(r'^accountToUpdate/',views.accountToUpdate),
    url(r'^accountToAdd/',views.accountToAdd,name='accountToAdd'),
    url(r'^accountAdd/',views.accountAdd,name='accountAdd'),
    url(r'^accountGetRecommderId/',views.accountGetRecommderId),
    url(r'^accountCheckName/',views.accountCheckName),
    url(r'^accountPause/',views.accountPause),
]

App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    # 资费模块
    # 遍历数据 costlist
    url(r'^costlist/', views.costlist, name='costlist'),
    #     删除数据 costdelete
    url(r'^costdelete/', views.costdetete),
    #     跳转到修改的页面
    url(r'^costload/', views.costload),
    #     修改
    url(r'^costupdate/', views.costupdate, name='costupdate'),
    #    跳转到添加页面
    url(r'^costToAdd/', views.costToAdd),
    #     添加
    url(r'^costadd/', views.costadd, name='costadd'),
    #     修改状态
    url(r'^changeFeeStatus/', views.changeFeeStatus, name='changeFeeStatus'),
    #    用户名字后台验证
    url(r'^costCheckName/',views.costCheckName),
]

Service/urls.py
from django.conf.urls import url

from Service import views

urlpatterns = [
    url(r'^servicelist/', views.servicelist, name='servicelist'),
    url(r'^serviceStart/',views.serviceStart),

]

netctoss/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^netctoss/',include('App.urls',namespace='netctoss')),
    url(r'^account/', include('Account.urls', namespace='account')),
    url(r'^service/',include('Service.urls',namespace='service')),
]

templates/netctoss/account/account_add.html
{{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>NetCTOSS</title>
        <link type="text/css" rel="stylesheet" media="all" href="{% static 'styles/global.css' %}" />
        <link type="text/css" rel="stylesheet" media="all" href="{% static 'styles/global_color.css' %}" />
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>



        <script language="javascript" type="text/javascript">
            $(function () {
                $('#recommder_idcard').blur(function () {
                    var recommder_idcard = $(this).val();
                    alert(recommder_idcard);
                    $.get('/account/accountGetRecommderId/',
                        {'recommder_idcard':recommder_idcard},
                        function (data) {
                            if(data['status'] == 200){
                                alert(222);
                                $('#recommder_id_hidden').val(data['recommender_id']);
                            }
                        })
                })

                $('#realname').blur(function () {
                    var name = $(this).val().trim();
                    var reg = /^[\u4E00-\u9FA5a-zA-Z]{1,20}$/
                    if(reg.test(name)){
                        alert(111);
                        $.ajax(
                            {
                                url:'/account/accountCheckName/',
                                type:'get',
                                data:{'name':name},
                                dataType:'json',
                                success:function (data) {
                                    if(data['status'] == 200){
                                        $('#realname_info').html('用户名字可以使用').css('color','green');
                                    }else{
                                        $('#realname_info').html('用户名字已经存在').css('color','red');
                                    }
                                }
                            }
                        )
                    }else{
                        $('#realname_info').html('用户名字格式不正确').css('color','red');
                    }

                })
                
                $('#repeat_passwd').blur(function () {
                    var login_passwd = $('#login_passwd').val();
                    var repeat_passwd = $(this).val();
                    if(login_passwd == repeat_passwd){
                        $('#passwd_info').html('两次密码一致').css('color','green');
                    }else{
                        $('#passwd_info').html('两次密码不一致，请重新输入').css('color','red');
                    }
                })


            })






            //保存成功的提示信息
            function showResult() {
                showResultDiv(true);
                window.setTimeout("showResultDiv(false);", 3000);
            }
            function showResultDiv(flag) {
                var divResult = document.getElementById("save_result_info");
                if (flag)
                    divResult.style.display = "block";
                else
                    divResult.style.display = "none";
            }

            //显示选填的信息项
            function showOptionalInfo(imgObj) {
                var div = document.getElementById("optionalInfo");
                if (div.className == "hide") {
                    div.className = "show";
                    imgObj.src = "{% static 'images/hide.png' %}";
                }
                else {
                    div.className = "hide";
                    imgObj.src = "../images/show.png";
                }
            }
        </script>
    </head>
    <body>
        <!--Logo区域开始-->
        <div id="header">
            <img src="{% static 'images/log.png' %}" alt="logo" class="left"/>
            <a href="#">[退出]</a>            
        </div>
        <!--Logo区域结束-->
        <!--导航区域开始-->
        <div id="navi">
            <ul id="menu">
                <li><a href="../index.html" class="index_off"></a></li>
                <li><a href="../role/role_list.html" class="role_off"></a></li>
                <li><a href="../admin/admin_list.html" class="admin_off"></a></li>
                <li><a href="../fee/fee_list.html" class="fee_off"></a></li>
                <li><a href="{% url 'account:accountlist' %}" class="account_on"></a></li>
                <li><a href="../service/service_list.html" class="service_off"></a></li>
                <li><a href="../bill/bill_list.html" class="bill_off"></a></li>
                <li><a href="../report/report_list.html" class="report_off"></a></li>
                <li><a href="../user/user_info.html" class="information_off"></a></li>
                <li><a href="../user/user_modi_pwd.html" class="password_off"></a></li>
            </ul>
        </div>
        <!--导航区域结束-->
        <!--主要区域开始-->
        <div id="main">       
            <!--保存成功或者失败的提示消息-->     
            <div id="save_result_info" class="save_fail">保存失败，该身份证已经开通过账务账号！</div>
            <form action="{% url 'account:accountAdd' %}" method="post" class="main_form">
                {% csrf_token %}
                <!--必填项-->
                <div class="text_info clearfix"><span>姓名：</span></div>
                <div class="input_info">
                    <input type="text" value="" name="real_name" id="realname"/>
                    <span class="required">*</span>
                    <div class="validate_msg_long" id="realname_info">20长度以内的汉字、字母和数字的组合</div>
                </div>
                <div class="text_info clearfix"><span>身份证：</span></div>
                <div class="input_info">
                    <input type="text" value="" name="idcard_no" />
                    <span class="required">*</span>
                    <div class="validate_msg_long">正确的身份证号码格式</div>
                </div>
                <div class="text_info clearfix"><span>登录账号：</span></div>
                <div class="input_info">
                    <input type="text" value="" name="login_name"  />
                    <span class="required">*</span>
                    <div class="validate_msg_long">30长度以内的字母、数字和下划线的组合</div>
                </div>
                <div class="text_info clearfix"><span>密码：</span></div>
                <div class="input_info">
                    <input type="password"  name="login_passwd" id="login_passwd"/>
                    <span class="required">*</span>
                    <div class="validate_msg_long">30长度以内的字母、数字和下划线的组合</div>
                </div>
                <div class="text_info clearfix"><span>重复密码：</span></div>
                <div class="input_info">
                    <input type="password" name = "repeat_passwd" id="repeat_passwd"/>
                    <span class="required">*</span>
                    <div class="validate_msg_long" id = "passwd_info">两次密码必须相同</div>
                </div>     
                <div class="text_info clearfix"><span>电话：</span></div>
                <div class="input_info">
                    <input type="text" class="width200" name="telephone"/>
                    <span class="required">*</span>
                    <div class="validate_msg_medium">正确的电话号码格式：手机或固话</div>
                </div>                
                <!--可选项-->
                <div class="text_info clearfix"><span>可选项：</span></div>
                <div class="input_info">
                    <img src="{% static 'images/show.png' %}" alt="展开" onclick="showOptionalInfo(this);" />
                </div>
                <div id="optionalInfo" class="hide">
                    <div class="text_info clearfix"><span>推荐人身份证号码：</span></div>
                    <div class="input_info">
                        <input type="text" id="recommder_idcard"/>
                        <div class="validate_msg_long">正确的身份证号码格式</div>
                        <input type="hidden" id = "recommder_id_hidden" name="recommder_idcardno" value="">
                    </div>
                    <div class="text_info clearfix"><span>生日：</span></div>
                    <div class="input_info">
                        <input type="text" value="" name="birthday" readonly class="readonly" />
                    </div>
                    <div class="text_info clearfix"><span>Email：</span></div>
                    <div class="input_info">
                        <input type="text" class="width350" name="email"/>
                        <div class="validate_msg_tiny">50长度以内，合法的 Email 格式</div>
                    </div> 
                    <div class="text_info clearfix"><span>职业：</span></div>
                    <div class="input_info">
                        <select name="occupation">
                            <option>干部</option>
                            <option>学生</option>
                            <option>技术人员</option>
                            <option>其他</option>
                        </select>                        
                    </div>
                    <div class="text_info clearfix"><span>性别：</span></div>
                    <div class="input_info fee_type">
                        <input type="radio" value="0" name="sex" checked="checked" id="female" />
                        <label for="female">女</label>
                        <input type="radio" value="1" name="sex" id="male" />
                        <label for="male">男</label>
                    </div> 
                    <div class="text_info clearfix"><span>通信地址：</span></div>
                    <div class="input_info">
                        <input type="text" class="width350" name="mailaddress"/>
                        <div class="validate_msg_tiny">50长度以内</div>
                    </div> 
                    <div class="text_info clearfix"><span>邮编：</span></div>
                    <div class="input_info">
                        <input type="text" name="zipcode"/>
                        <div class="validate_msg_long">6位数字</div>
                    </div> 
                    <div class="text_info clearfix"><span>QQ：</span></div>
                    <div class="input_info">
                        <input type="text" name="qq"/>
                        <div class="validate_msg_long">5到13位数字</div>
                    </div>                
                </div>
                <!--操作按钮-->
                <div class="button_info clearfix">
                    <input type="submit" value="保存" class="btn_save"/>
                    <input type="button" value="取消" class="btn_save" />
                </div>
            </form>  
        </div>
        <!--主要区域结束-->
        <div id="footer">
          
        </div>
    </body>
</html>

templates/netctoss/account/account_detail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>NetCTOSS</title>
        <link type="text/css" rel="stylesheet" media="all" href="../styles/global.css" />
        <link type="text/css" rel="stylesheet" media="all" href="../styles/global_color.css" />
    </head>
    <body>
        <!--Logo区域开始-->
        <div id="header">
            <img src="../images/logo.png" alt="logo" class="left" />
            <a href="#">[退出]</a>            
        </div>
        <!--Logo区域结束-->
        <!--导航区域开始-->
        <div id="navi">
            <ul id="menu">
                <li><a href="../index.html" class="index_off"></a></li>
                <li><a href="../role/role_list.html" class="role_off"></a></li>
                <li><a href="../admin/admin_list.html" class="admin_off"></a></li>
                <li><a href="../fee/fee_list.html" class="fee_off"></a></li>
                <li><a href="../account/account_list.html" class="account_on"></a></li>
                <li><a href="../service/service_list.html" class="service_off"></a></li>
                <li><a href="../bill/bill_list.html" class="bill_off"></a></li>
                <li><a href="../report/report_list.html" class="report_off"></a></li>
                <li><a href="../user/user_info.html" class="information_off"></a></li>
                <li><a href="../user/user_modi_pwd.html" class="password_off"></a></li>
            </ul>
        </div>
        <!--导航区域结束-->
        <!--主要区域开始-->
        <div id="main">            
            <form action="" method="" class="main_form">
                <!--必填项-->
                <div class="text_info clearfix"><span>账务账号ID：</span></div>
                <div class="input_info"><input type="text" value="10" readonly class="readonly" /></div>
                <div class="text_info clearfix"><span>姓名：</span></div>
                <div class="input_info"><input type="text" value="张三" readonly class="readonly" /></div>
                <div class="text_info clearfix"><span>身份证：</span></div>
                <div class="input_info">
                    <input type="text" value="230198765432123456" readonly class="readonly" />
                </div>
                <div class="text_info clearfix"><span>登录账号：</span></div>
                <div class="input_info">
                    <input type="text" value="user1" readonly class="readonly" />
                </div>                   
                <div class="text_info clearfix"><span>电话：</span></div>
                <div class="input_info">
                    <input type="text" class="width200 readonly" readonly value="13687865435" />
                </div>
                <div class="text_info clearfix"><span>推荐人账务账号ID：</span></div>
                <div class="input_info"><input type="text" readonly class="readonly" value="5" /></div>
                <div class="text_info clearfix"><span>推荐人身份证号码：</span></div>
                <div class="input_info"><input type="text" readonly class="readonly" value="230198765432123456" /></div>
                <div class="text_info clearfix"><span>状态：</span></div>
                <div class="input_info">
                    <select disabled>
                        <option>开通</option>
                        <option>暂停</option>
                        <option>删除</option>
                    </select>                        
                </div>                    
                <div class="text_info clearfix"><span>开通/暂停/删除时间：</span></div>
                <div class="input_info"><input type="text" readonly class="readonly" value="2013/01/21 12:00:00" /></div>

                <div class="text_info clearfix"><span>上次登录时间：</span></div>
                <div class="input_info"><input type="text" readonly class="readonly" value="2013/02/21 12:00:00" /></div>
                <div class="text_info clearfix"><span>上次登录IP：</span></div>
                <div class="input_info"><input type="text" readonly class="readonly" value="192.168.0.100" /></div>
                <!--可选项数据-->
                <div class="text_info clearfix"><span>生日：</span></div>
                <div class="input_info">
                    <input type="text" readonly class="readonly" value="1980/01/21，由身份证计算而来" />
                </div>
                <div class="text_info clearfix"><span>Email：</span></div>
                <div class="input_info">
                    <input type="text" class="width350 readonly" readonly value="aa@aa.com" />
                </div> 
                <div class="text_info clearfix"><span>职业：</span></div>
                <div class="input_info">
                    <select disabled>
                        <option>干部</option>
                        <option>学生</option>
                        <option>技术人员</option>
                        <option>其他</option>
                    </select>                        
                </div>
                <div class="text_info clearfix"><span>性别：</span></div>
                <div class="input_info fee_type">
                    <input type="radio" name="radSex" checked="checked" id="female" disabled />
                    <label for="female">女</label>
                    <input type="radio" name="radSex" id="male" disabled />
                    <label for="male">男</label>
                </div> 
                <div class="text_info clearfix"><span>通信地址：</span></div>
                <div class="input_info"><input type="text" class="width350 readonly" readonly value="北京市海淀区北三环中路甲18号中鼎大厦" /></div> 
                <div class="text_info clearfix"><span>邮编：</span></div>
                <div class="input_info"><input type="text" class="readonly" readonly value="100098" /></div> 
                <div class="text_info clearfix"><span>QQ：</span></div>
                <div class="input_info"><input type="text" class="readonly" readonly value="12345678" /></div>                
                <!--操作按钮-->
                <div class="button_info clearfix">
                    <input type="button" value="返回" class="btn_save" onclick="location.href='account_list.html';" />
                </div>
            </form>  
        </div>
        <!--主要区域结束-->
        <div id="footer">
           
        </div>
    </body>
</html>

templates/netctoss/account/account_list.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>NetCTOSS</title>
        <link type="text/css" rel="stylesheet" media="all" href="{% static 'styles/global.css' %}" />
        <link type="text/css" rel="stylesheet" media="all" href="{% static 'styles/global_color.css' %}" />
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>

        <script language="javascript" type="text/javascript">
            $(function () {
                $('.accountdelete').click(function () {
                    var $input = $(this);

                    var accountid = $input.parent('td').parent('tr').find('td').html();
                    $.get('/account/accountdelete/',
                         {'accountid':accountid},
                         function (data) {
                             if(data['status'] == 200){
                                 var $td = $input.parent('td');
                                 $td.html('');
                                 $td.prev().prev().prev().html('删除');

                             }
                         })
                })

                $('.accountstart').click(function () {
                    var $input = $(this);

                    var accountid = $input.parent('td').parent('tr').find('td').html();

                    $.get('/account/accountstart/',
                        {'accountid':accountid},
                        function (data) {
                            if(data['status'] == 200){
                                var $td = $input.parent('td');
                                $td.html('<input type="button" value="暂停" class="btn_pause accountstart" />');
                                 $td.prev().prev().prev().html('开通');
                            }
                        })
                })

                $('.accountpause').click(function () {
                    //点击之后 要将当前对象的状态修改为1  并且要将状态栏的值修改为 暂停
                    //操作里的内容修改为开通

                    var $input = $(this);
                    var accountid = $input.parent('td').parent('tr').find('td').html();
                    $.post('/account/accountPause/',
                        {'accountid':accountid},
                        function (data) {
                        //'10'  10   == true
                            //'10'  10  === false
                             if(data['status'] == 200){
                                var $td = $input.parent('td');
                                $td.html('<input type="button" value="开通" class="btn_start accountstart" />\n' +
                                    '     <input type="button" value="修改" class="btn_modify" onclick="toUpdate({{ account.id }})" />\n' +
                                    '     <input type="button" value="删除" class="btn_delete accountdelete" />');
                                $td.prev().prev().prev().html('暂停');
                             }
                        }
                    )

                })
            })

            function toUpdate(id) {
                window.location.href='/account/accountToUpdate/?id='+id

            }





            //删除
            function deleteAccount(id) {
                var r = window.confirm("确定要删除此账务账号吗？\r\n删除后将不能恢复，且会删除其下属的所有业务账号。");


            }
            //开通或暂停
            function setState() {
                var r = window.confirm("确定要开通此账务账号吗？");
                document.getElementById("operate_result_info").style.display = "block";
            }
        </script>
    </head>
    <body>
        <!--Logo区域开始-->
        <div id="header">
            <img src="{% static 'images/log.png' %}" alt="logo" class="left"/>
            <a href="#">[退出]</a>            
        </div>
        <!--Logo区域结束-->
        <!--导航区域开始-->
        <div id="navi">                        
            <ul id="menu">
                <li><a href="../index.html" class="index_off"></a></li>
                <li><a href="../role/role_list.html" class="role_off"></a></li>
                <li><a href="../admin/admin_list.html" class="admin_off"></a></li>
                <li><a href="{% url 'netctoss:costlist' %}" class="fee_off"></a></li>
                <li><a href="{% url 'account:accountlist' %}" class="account_on"></a></li>
                <li><a href="{% url 'service:servicelist' %}" class="service_off"></a></li>
                <li><a href="../bill/bill_list.html" class="bill_off"></a></li>
                <li><a href="../report/report_list.html" class="report_off"></a></li>
                <li><a href="../user/user_info.html" class="information_off"></a></li>
                <li><a href="../user/user_modi_pwd.html" class="password_off"></a></li>
            </ul>            
        </div>
        <!--导航区域结束-->
        <!--主要区域开始-->
        <div id="main">
            <form action="{% url 'account:accountlist' %}" method="post">
                {% csrf_token %}
                <!--查询-->
                <div class="search_add">                        
                    <div>身份证：<input type="text" name="idcard_no"  placeholder="不验证" class="text_search" /></div>
                    <div>姓名：<input type="text" name="real_name" class="width70 text_search" placeholder="不验证" /></div>
                    <div>登录名：<input type="text" name="login_name" placeholder="不验证" class="text_search" /></div>
                    <div>
                        状态：
                        <select class="select_search" name="status">
                            <option value="">全部</option>
                            <option value="0">开通</option>
                            <option value="1">暂停</option>
                            <option value="2">删除</option>
                        </select>
                    </div>
                    <div><input type="submit" value="搜索" class="btn_search" /></div>
                    <input type="button" value="增加" class="btn_add" onclick="location.href='{% url 'account:accountToAdd' %}';" />
                </div>  
                <!--删除等的操作提示-->
                <div id="operate_result_info" class="operate_success">
                    <img src="../images/close.png" onclick="this.parentNode.style.display='none';" />
                    删除成功，且已删除其下属的业务账号！
                </div>   
                <!--数据区域：用表格展示数据-->     
                <div id="data">            
                    <table id="datalist">
                    <tr>
                        <th>账号ID</th>
                        <th>姓名</th>
                        <th class="width150">身份证</th>
                        <th>登录名</th>
                        <th>状态</th>
                        <th class="width100">创建日期</th>
                        <th class="width150">上次登录时间</th>                                                        
                        <th class="width200"></th>
                    </tr>

                    {% for account in p.object_list %}
                        <tr>
                            <td>{{ account.id }}</td>
                            <td><a href="account_detail.html">{{ account.real_name }}</a></td>
                            <td>{{ account.idcard_no }}</td>
                            <td>{{ account.login_name }}</td>
                            {% if account.status == '0' %}
                                    <td>开通</td>
                                {% elif account.status == '1' %}
                                    <td>暂停</td>
                                {% else %}
                                    <td>删除</td>
                            {% endif %}

                            <td>{{ account.create_date }}</td>
                            <td>{{ account.last_login_time }}</td>
                            {% if account.status == '2' %}
                                <td></td>
                                {% elif account.status == '1' %}
                                    <td class="td_modi">
                                        <input type="button" value="开通" class="btn_start accountstart" />
                                        <input type="button" value="修改" class="btn_modify" onclick="toUpdate({{ account.id }})" />
                                        <input type="button" value="删除" class="btn_delete accountdelete" />
                                    </td>
                                {% else %}
                                    <td class="td_modi">
                                        <input type="button" value="暂停" class="btn_pause accountpause"/>
                                    </td>

                            {% endif %}

                        </tr>
                    {% endfor %}


                </table>
                <p>业务说明：<br />
                1、创建则开通，记载创建时间；<br />
                2、暂停后，记载暂停时间；<br />
                3、重新开通后，删除暂停时间；<br />
                4、删除后，记载删除时间，标示为删除，不能再开通、修改、删除；<br />
                5、暂停账务账号，同时暂停下属的所有业务账号；<br />                
                6、暂停后重新开通账务账号，并不同时开启下属的所有业务账号，需要在业务账号管理中单独开启；<br />
                7、删除账务账号，同时删除下属的所有业务账号。</p>
                </div>                   
                <!--分页-->
                <div id="pages">
                    <a href="{% url 'account:accountlist' %}?page=1">首页</a>
                    {% if p.has_previous %}
                        <a href="{% url 'account:accountlist' %}?page={{ p.previous_page_number }}">上一页</a>
                        {% else %}
                        <a href="#">上一页</a>
                    {% endif %}

                    {% for p1 in pagin.page_range %}
                        {% ifequal p1 pn %}
                            <a href="{% url 'account:accountlist' %}?page={{ p1 }}" class="current_page">{{ p1 }}</a>
                            {% else %}
                            <a href="{% url 'account:accountlist' %}?page={{ p1 }}">{{ p1 }}</a>
                        {% endifequal %}

                    {% endfor %}



                    {% if p.has_next %}
                         <a href="{% url 'account:accountlist' %}?page={{ p.next_page_number }}&search_dict={{ search_dict }}">下一页</a>
                        {% else %}
                         <a href="#">下一页</a>
                    {% endif %}

                    <a href="{% url 'account:accountlist' %}?page={{ pagin.num_pages }}">末页</a>
                </div>                    
            </form>
        </div>
        <!--主要区域结束-->
        <div id="footer">
           
        </div>
    </body>
</html>