Acount/urls.py
from django.conf.urls import url

from Account import views

urlpatterns = [
    url(r'^accountlist/', views.accountlist, name='accountlist'),
    url(r'^accountdelete/',views.accountdelete),
    url(r'^accountstart/',views.accountstart),
    url(r'^accountToUpdate/',views.accountToUpdate),
    url(r'^accountToAdd/',views.accountToAdd,name='accountToAdd'),
    url(r'^accountAdd/',views.accountAdd,name='accountAdd'),
    url(r'^accountGetRecommderId/',views.accountGetRecommderId),
    url(r'^accountCheckName/',views.accountCheckName),
    url(r'^accountPause/',views.accountPause),
]

App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    # 资费模块
    # 遍历数据 costlist
    url(r'^costlist/', views.costlist, name='costlist'),
    #     删除数据 costdelete
    url(r'^costdelete/', views.costdetete),
    #     跳转到修改的页面
    url(r'^costload/', views.costload),
    #     修改
    url(r'^costupdate/', views.costupdate, name='costupdate'),
    #    跳转到添加页面
    url(r'^costToAdd/', views.costToAdd),
    #     添加
    url(r'^costadd/', views.costadd, name='costadd'),
    #     修改状态
    url(r'^changeFeeStatus/', views.changeFeeStatus, name='changeFeeStatus'),
    #    用户名字后台验证
    url(r'^costCheckName/',views.costCheckName),
]

Service/urls.py
from django.conf.urls import url

from Service import views

urlpatterns = [
    url(r'^servicelist/', views.servicelist, name='servicelist'),
    url(r'^serviceStart/',views.serviceStart),

]

netctoss/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^netctoss/',include('App.urls',namespace='netctoss')),
    url(r'^account/', include('Account.urls', namespace='account')),
    url(r'^service/',include('Service.urls',namespace='service')),
]

templates/netctoss/fee/fee_add.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>NetCTOSS</title>
        <link type="text/css" rel="stylesheet" media="all" href="{% static 'styles/global.css' %}" />
        <link type="text/css" rel="stylesheet" media="all" href="{% static 'styles/global_color.css' %}" />
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script language="javascript" type="text/javascript">

            
            $(function () {
                $('#name').blur(function () {
                    var name = $(this).val();
                    //判断输入的内容是否满足正则表达式
                    // 如果满足提示用户名字可以使用  并且显示绿色字体
                    //如果不满足 提示 用户名子格式不正确  并且显示红色字体
                    //匹配帐号是否合法(字母开头，允许5-16字节，允许字母数字下划线)：
                    {#var reg = /^[a-zA-Z][a-zA-Z0-9_]{4,15}$/;#}
                    var reg = /^[a-z]{3,6}$/
                    //判断字符串是否满足该正则表达式 test方法如果满足返回true
                    //不满足返回false
                    if(reg.test(name)){
                        {#$('#nameinfo').html('用户名字可以使用').css('color','green');#}
                       //去数据库访问   查看名字是否存在 如果存在返回用户名字已存在，请重新填写
                        //如果不存在用户名字可以使用
                        $.get('/netctoss/costCheckName/',
                              {'name':name},
                               function (data) {
                                   if(data['status']==200){
                                       $('#nameinfo').html(data['msg']).css('color','green');
                                   }else{
                                       $('#nameinfo').html(data['msg']).css('color','red');
                                   }
                               })


                    }else{
                        $('#nameinfo').html('用户名子格式不正确').css('color','red');
                    }
                })
            })



            

            function parse() {

                var base_duration = $('#base_duration').val();
                var reg = /^[0-9]{3,5}$/;
                if(reg.test(base_duration)) {
                    alert(111)
                    return true

                }else{
                    alert(222)
                    return false
                }


                //onsubmit 的函数的返回值是true了 那么就可以提交  否则是false不可以提交
                {#return true#}
            }



            //保存结果的提示
            function showResult() {
                showResultDiv(true);
                window.setTimeout("showResultDiv(false);", 3000);
            }
            function showResultDiv(flag) {
                var divResult = document.getElementById("save_result_info");
                if (flag)
                    divResult.style.display = "block";
                else
                    divResult.style.display = "none";
            }

            //切换资费类型
            function feeTypeChange(type) {
                var inputArray = document.getElementById("main").getElementsByTagName("input");
                if (type == 1) {
                    inputArray[4].readonly = true;
                    inputArray[4].value = "";
                    inputArray[4].className += " readonly";
                    inputArray[5].readonly = false;
                    inputArray[5].className = "width100";
                    inputArray[6].readonly = true;
                    inputArray[6].className += " readonly";
                    inputArray[6].value = "";
                }
                else if (type == 2) {
                    inputArray[4].readonly = false;
                    inputArray[4].className = "width100";
                    inputArray[5].readonly = false;
                    inputArray[5].className = "width100";
                    inputArray[6].readonly = false;
                    inputArray[6].className = "width100";
                }
                else if (type == 3) {
                    inputArray[4].readonly = true;
                    inputArray[4].value = "";
                    inputArray[4].className += " readonly";
                    inputArray[5].readonly = true;
                    inputArray[5].value = "";
                    inputArray[5].className += " readonly";
                    inputArray[6].readonly = false;
                    inputArray[6].className = "width100";
                }
            }
        </script>
    </head>
    <body>
        <!--Logo区域开始-->
        <div id="header">
            <img src="../images/logo.png" alt="logo" class="left"/>
            <a href="#">[退出]</a>            
        </div>
        <!--Logo区域结束-->
        <!--导航区域开始-->
        <div id="navi">
            <ul id="menu">
                <li><a href="../index.html" class="index_off"></a></li>
                <li><a href="../role/role_list.html" class="role_off"></a></li>
                <li><a href="../admin/admin_list.html" class="admin_off"></a></li>
                <li><a href="{% url 'netctoss:costlist'%}" class="fee_on"></a></li>
                <li><a href="../account/account_list.html" class="account_off"></a></li>
                <li><a href="../service/service_list.html" class="service_off"></a></li>
                <li><a href="../bill/bill_list.html" class="bill_off"></a></li>
                <li><a href="../report/report_list.html" class="report_off"></a></li>
                <li><a href="../user/user_info.html" class="information_off"></a></li>
                <li><a href="../user/user_modi_pwd.html" class="password_off"></a></li>
            </ul>
        </div>
        <!--导航区域结束-->
        <!--主要区域开始-->
        <div id="main">            
            <div id="save_result_info" class="save_fail">保存失败，资费名称重复！</div>
            <form action="{% url 'netctoss:costadd' %}" method="post" class="main_form" onsubmit="return parse();">
                {% csrf_token %}
                <div class="text_info clearfix"><span>资费名称：</span></div>
                <div class="input_info">
                    <input type="text" name="name" class="width300" value="" id="name"/>
                    <span class="required">*</span>
                    <div class="validate_msg_short" id="nameinfo">50长度的字母、数字、汉字和下划线的组合</div>
                </div>
                <div class="text_info clearfix"><span>资费类型：</span></div>
                <div class="input_info fee_type">
                    <input type="radio" name="cost_type" id="monthly" onclick="feeTypeChange(1);" />
                    <label for="monthly">包月</label>
                    <input type="radio" name="cost_type" checked="checked" id="package" onclick="feeTypeChange(2);" />
                    <label for="package">套餐</label>
                    <input type="radio" name="cost_type" id="timeBased" onclick="feeTypeChange(3);" />
                    <label for="timeBased">计时</label>
                </div>
                <div class="text_info clearfix"><span>基本时长：</span></div>
                <div class="input_info">
                    <input type="text" name="base_duration" value="" class="width100" id="base_duration"/>
                    <span class="info">小时</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long">1-600之间的整数</div>
                </div>
                <div class="text_info clearfix"><span>基本费用：</span></div>
                <div class="input_info">
                    <input type="text" name = "base_cost" value="" class="width100" />
                    <span class="info">元</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long error_msg">0-99999.99之间的数值</div>
                </div>
                <div class="text_info clearfix"><span>单位费用：</span></div>
                <div class="input_info">
                    <input type="text" name="unit_cost" value="" class="width100" />
                    <span class="info">元/小时</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long error_msg">0-99999.99之间的数值</div>
                </div>
                <div class="text_info clearfix"><span>资费说明：</span></div>
                <div class="input_info_high">
                    <textarea class="width300 height70" name="descr"></textarea>
                    <div class="validate_msg_short error_msg">100长度的字母、数字、汉字和下划线的组合</div>
                </div>                    
                <div class="button_info clearfix">
                    <input type="submit" value="保存" class="btn_save" />
                    <input type="button" value="取消" class="btn_save" onclick="location.href='/netctoss/costToAdd/'"/>
                </div>
            </form>  
        </div>
        <!--主要区域结束-->
        <div id="footer">
           
        </div>
    </body>
</html>

templates/netctoss/fee/fee_list.html
{% load static%}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>NetCTOSS</title>
        <link type="text/css" rel="stylesheet" media="all" href="{% static 'styles/global.css' %}" />
        <link type="text/css" rel="stylesheet" media="all" href="{% static 'styles/global_color.css' %}" />
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script language="javascript" type="text/javascript">
{#            启动#}
{#            ajax 其实质是利用ajax对象（xmlhttprequset = xhr）异步向服务器发送请求，返回的部分数据#}
{#整个过程无刷新 不打断用户操作#}
{#            jquery   封装了js文件#}
{#            ajax发送请求   jquery 就是js  就是操作标签的#}

            $(function(){
                $('.startFee').click(function () {
                    var $input = $(this);
                    //找到当前对象的id
                        var cost_id = $input.parent('td').parent('tr').find('td').html();
                        //发送请求 通过id找到对象 然后修改状态
                    // getJSON(url,{参数}，function(data){})  data就是返回的json数据
                        $.getJSON('/netctoss/changeFeeStatus/',
                                    {'cost_id':cost_id},
                                    function (data) {
                                        if(data['status'] == 200){

                                            var $td = $input.parent('td');
                                            //将input标签的父标签的内容清空
                                            $td.html('');
                                            //将input的标签的父标签的上一个标签该为开通
                                            $td.prev().html('开通');
                                        }
                                    }
                        )

                })
            })

            
            
            
            
            //排序按钮的点击事件
            function sort(btnObj) {


                //sort_rule  asc  desc
                //type  月租  基费  时长
                var type = btnObj.value;
                if(type == '月租'){
                    if (btnObj.className == "sort_desc") {
                        window.location.href='/netctoss/costlist/?sort_rule='+'sort_desc'
                        btnObj.className = "sort_asc";

                    }else{
                        window.location.href='/netctoss/costlist/?sort_rule='+'sort_asc'
                        btnObj.className = "sort_desc";
                    }
                }


            }

            function addFee() {
                window.location.href='/netctoss/costToAdd/'
            }


            //启用
            function startFee() {
                var r = window.confirm("确定要启用此资费吗？资费启用后将不能修改和删除。");
                document.getElementById("operate_result_info").style.display = "block";
            }
            //修改
            function updateFee(id) {
                window.location.href='/netctoss/costload/?id='+id;
            }


            //删除
            function deleteFee(id,page) {
                {#window.confirm 的方法返回值是bool  如果点击确定返回的是true 点击取消返回的是false#}
                var r = window.confirm("确定要删除此资费吗？");
                if(r){
                    {#点击删除 如果获取当前对象的id#}

                    window.location.href='/netctoss/costdelete?id=' + id + '&page=' + page
                    {#window.open('/netctoss/costdelete/?id='+id,target='_self');#}

                }else{
                    document.getElementById("operate_error_info").style.display = "block";

                }
            }
        </script>        
    </head>
    <body>
        <!--Logo区域开始-->
        <div id="header">
            <img src="{% static 'images/log.png' %}" alt="logo" class="left"/>
			<span>当前账号：<b>scott</b></span>
            <a href="#">[退出]</a>            
        </div>
        <!--Logo区域结束-->
        <!--导航区域开始-->
        <div id="navi">                        
            <ul id="menu">
                <li><a href="../index.html" class="index_off"></a></li>
                <li><a href="../role/role_list.html" class="role_off"></a></li>
                <li><a href="../admin/admin_list.html" class="admin_off"></a></li>
                <li><a href="{% url 'netctoss:costlist'%}" class="fee_on"></a></li>
                <li><a href="{% url 'account:accountlist' %}" class="account_off"></a></li>
                <li><a href="{% url 'service:servicelist' %}" class="service_off"></a></li>
                <li><a href="../bill/bill_list.html" class="bill_off"></a></li>
                <li><a href="../report/report_list.html" class="report_off"></a></li>
                <li><a href="../user/user_info.html" class="information_off"></a></li>
                <li><a href="../user/user_modi_pwd.html" class="password_off"></a></li>
            </ul>            
        </div>
        <!--导航区域结束-->
        <!--主要区域开始-->
        <div id="main">
            <form action="" method="">
                <!--排序-->
                <div class="search_add">
                    <div>
                        <input type="button" value="月租" class="{{ sort_rule }}" onclick="sort(this);" />
                        <input type="button" value="基费" class="sort_asc" onclick="sort(this);" />
                        <input type="button" value="时长" class="sort_asc" onclick="sort(this);" />
                    </div>
                    <input type="button" value="增加" class="btn_add" onclick="addFee();" />
                </div> 
                <!--启用操作的操作提示-->
                <div id="operate_result_info" class="operate_success">
                    <img src="../images/close.png" onclick="this.parentNode.style.display='none';" />
                    删除成功！
                </div>
                <div id="operate_error_info" class="operate_fail" hidden="true">
                    <img src="../images/close.png" onclick="this.parentNode.style.display='none';" />
                    删除失败！
                </div>
                <!--数据区域：用表格展示数据-->     
                <div id="data">            
                    <table id="datalist">
                        <tr>
                            <th>资费ID</th>
                            <th class="width100">资费名称</th>
                            <th>基本时长</th>
                            <th>基本费用</th>
                            <th>单位费用</th>
                            <th>创建时间</th>
                            <th>开通时间</th>
                            <th class="width50">状态</th>
                            <th class="width200"></th>
                        </tr>                      
                        {% for cost in p.object_list %}
                             <tr>
                                    <td>{{ cost.id }}</td>
                                    <td><a href="fee_detail.html">{{ cost.name }}</a></td>
                                    <td>{{ cost.base_duration }}</td>
                                    <td>{{ cost.base_cost }}</td>
                                    <td>{{ cost.unit_cost }}</td>
                                    <td>{{ cost.creatime }}</td>
                                    <td>{{ cost.startime }}</td>
                                    {% if cost.status == '0'%}
                                            <td>暂停</td>
                                        {% else %}
                                            <td>开通</td>
                                    {% endif %}

                                    {% if cost.status == '1' %}
                                        <td></td>
                                        {% else %}
                                        <td>
                                            <input type="button" value="启用" class="btn_start startFee"/>
                                            <input type="button" value="修改" class="btn_modify" onclick="updateFee({{ cost.id }});" />
                                            <input type="button" value="删除" class="btn_delete" onclick="deleteFee({{ cost.id }},{{ pn }});" />
                                        </td>

                                    {% endif %}

                        </tr>
                        {% endfor %}


                    </table>
                    <p>业务说明：<br />
                    1、创建资费时，状态为暂停，记载创建时间；<br />
                    2、暂停状态下，可修改，可删除；<br />
                    3、开通后，记载开通时间，且开通后不能修改、不能再停用、也不能删除；<br />
                    4、业务账号修改资费时，在下月底统一触发，修改其关联的资费ID（此触发动作由程序处理）
                    </p>
                </div>
                <!--分页-->
                <div id="pages">
                    {% if p.has_previous %}
                        <a href="{% url 'netctoss:costlist' %}?page={{ p.previous_page_number }}&sort_rule={{ page_sort_rule }}">上一页</a>
                        {% else %}
                        <a href="#">上一页</a>
                    {% endif %}

                    {% for p1 in pagin.page_range %}
                        {% if pn == p1 %}
                             <a href="{% url 'netctoss:costlist' %}?page={{ p1 }}&sort_rule={{ page_sort_rule }}" class="current_page">{{ p1 }}</a>
                            {% else %}
                             <a href="{% url 'netctoss:costlist' %}?page={{ p1 }}&sort_rule={{ page_sort_rule }}">{{ p1 }}</a>


                        {% endif %}

                    {% endfor %}

                    {% if p.has_next %}
                        <a href="{% url 'netctoss:costlist' %}?page={{ p.next_page_number }}&sort_rule={{ page_sort_rule }}">下一页</a>
                        {% else %}
                        <a href="#">下一页</a>
                    {% endif %}

                </div>
            </form>
        </div>
        <!--主要区域结束-->
        <div id="footer">
          
        </div>
    </body>
</html>

templates/netctoss/fee/fee_modi.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>NetCTOSS</title>
        <link type="text/css" rel="stylesheet" media="all" href="{% static 'styles/global.css' %}" />
        <link type="text/css" rel="stylesheet" media="all" href="{% static 'styles/global_color.css' %}" />
        <script language="javascript" type="text/javascript">
            //保存结果的提示
            function showResult() {
                showResultDiv(true);
                window.setTimeout("showResultDiv(false);", 3000);
            }
            function showResultDiv(flag) {
                var divResult = document.getElementById("save_result_info");
                if (flag)
                    divResult.style.display = "block";
                else
                    divResult.style.display = "none";
            }

            //切换资费类型
            function feeTypeChange(type) {
                var inputArray = document.getElementById("main").getElementsByTagName("input");
                if (type == 1) {
                    inputArray[5].readonly = true;
                    inputArray[5].value = "";
                    inputArray[5].className += " readonly";
                    inputArray[6].readonly = false;
                    inputArray[6].className = "width100";
                    inputArray[7].readonly = true;
                    inputArray[7].className += " readonly";
                    inputArray[7].value = "";
                }
                else if (type == 2) {
                    inputArray[5].readonly = false;
                    inputArray[5].className = "width100";
                    inputArray[6].readonly = false;
                    inputArray[6].className = "width100";
                    inputArray[7].readonly = false;
                    inputArray[7].className = "width100";
                }
                else if (type == 3) {
                    inputArray[5].readonly = true;
                    inputArray[5].value = "";
                    inputArray[5].className += " readonly";
                    inputArray[6].readonly = true;
                    inputArray[6].value = "";
                    inputArray[6].className += " readonly";
                    inputArray[7].readonly = false;
                    inputArray[7].className = "width100";
                }
            }
        </script>
    </head>
    <body>
        <!--Logo区域开始-->
        <div id="header">
            <img src="{% static 'images/log.png' %}" alt="logo" class="left"/>
            <a href="#">[退出]</a>            
        </div>
        <!--Logo区域结束-->
        <!--导航区域开始-->
        <div id="navi">
            <ul id="menu">
                <li><a href="../index.html" class="index_off"></a></li>
                <li><a href="../role/role_list.html" class="role_off"></a></li>
                <li><a href="../admin/admin_list.html" class="admin_off"></a></li>
                <li><a href="../fee/fee_list.html" class="fee_on"></a></li>
                <li><a href="../account/account_list.html" class="account_off"></a></li>
                <li><a href="../service/service_list.html" class="service_off"></a></li>
                <li><a href="../bill/bill_list.html" class="bill_off"></a></li>
                <li><a href="../report/report_list.html" class="report_off"></a></li>
                <li><a href="../user/user_info.html" class="information_off"></a></li>
                <li><a href="../user/user_modi_pwd.html" class="password_off"></a></li>
            </ul>
        </div>
        <!--导航区域结束-->
        <!--主要区域开始-->
        <div id="main">            
            <div id="save_result_info" class="save_success">保存成功！</div>
            <form action="{% url 'netctoss:costupdate' %}?id={{ cost.id }}" method="post" class="main_form">
                {% csrf_token %}
                <div class="text_info clearfix"><span>资费ID：</span></div>
                <div class="input_info">
                    <input type="text" name="id" class="readonly" readonly value="{{ cost.id }}" />
                </div>
                <div class="text_info clearfix"><span>资费名称：</span></div>
                <div class="input_info">
                    <input type="text" name="name" class="width300" value="{{ cost.name }}"/>
                    <span class="required">*</span>
                    <div class="validate_msg_short">50长度的字母、数字、汉字和下划线的组合</div>
                </div>
                <div class="text_info clearfix"><span>资费类型：</span></div>
                <div class="input_info fee_type">
                    <input type="radio" name="cost_type" id="monthly" onclick="feeTypeChange(1);" />
                    <label for="monthly">包月</label>
                    <input type="radio" name="cost_type" checked="checked" id="package" onclick="feeTypeChange(2);" />
                    <label for="package">套餐</label>
                    <input type="radio" name="cost_type" id="timeBased" onclick="feeTypeChange(3);" />
                    <label for="timeBased">计时</label>
                </div>
                <div class="text_info clearfix"><span>基本时长：</span></div>
                <div class="input_info">
                    <input type="text" name = "base_duration" value="{{ cost.base_duration }}" class="width100" />
                    <span class="info">小时</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long">1-600之间的整数</div>
                </div>
                <div class="text_info clearfix"><span>基本费用：</span></div>
                <div class="input_info">
                    <input type="text" name="base_cost" value="{{ cost.base_cost }}" class="width100" />
                    <span class="info">元</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long">0-99999.99之间的数值</div>
                </div>
                <div class="text_info clearfix"><span>单位费用：</span></div>
                <div class="input_info">
                    <input type="text" name="unit_cost" value="{{ cost.unit_cost }}" class="width100" />
                    <span class="info">元/小时</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long">0-99999.99之间的数值</div>
                </div>   
                <div class="text_info clearfix"><span>资费说明：</span></div>
                <div class="input_info_high">
                    <textarea class="width300 height70" name="descr">{{ cost.descr }}
                    </textarea>
                    <div class="validate_msg_short">100长度的字母、数字、汉字和下划线的组合</div>
                </div>                    
                <div class="button_info clearfix">
                    <button  value="保存" class="btn_save">保存</button>
                    <button  value="取消" class="btn_save">取消</button>
                </div>
            </form>
        </div>
        <!--主要区域结束-->
        <div id="footer">
            
        </div>
    </body>
</html>